server:
  port: 8090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8091
          predicates:
            - Path=/order/**
        - id: product-service
          uri: http://localhost:8092
          predicates:
            - Path=/product/**
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

  security:
    oauth2:
      resource-server:
        jwt:
          public-key-location: classpath:/keys/public.pem
